algoritmo "cotação do dolar"
// Função :calcular a cotação do dolar
// Autor : JoãoVitor
// Data : 10/03/2020
// Seção de Declarações 
var
d,valor,tot :real

inicio
// entrada
escreval ("solicite o valor do dolar ")
leia (d)
 escreval("solicite o valor que deseja converter ")
leia (valor)
//processamento
tot <- (valor/d)
//saida
escreval ("o valor para o real sera de r$", tot)


fimalgoritmo
